### ISSUE TITLE
Integration with multiprocessing to download all NSE data

### ISSUE THREAD

**Issue by pkjmesra** [pkjmesra/PKNSETools#3]

**Comment by DhavalThkkar** [comment]
Can't we use `celery` or `prefect` to manage these efficiently?

**Comment by pkjmesra** [comment]
Sure. We can. This data can be both intraday or daily data for more than a year. It can be for during market hours or off market hours.

BTW, at this time, you can download all NSE data following the menu options D > S in PKScreener : https://github.com/pkjmesra/PKScreener/releases
